// Indices, gold, forex and global equities come from Yahoo; crypto from
// CoinGecko. The IPO calendar is the one section still on mock data.
const cryptoService = require('./cryptoService');
const globalMarketService = require('./globalMarketService');
const indianMarketService = require('./indianMarketService');
const geminiService = require('./geminiService');
const newsService = require('./newsService');

function jitter(base, pct = 2) {
  const delta = base * (pct / 100) * (Math.random() * 2 - 1);
  return Number((base + delta).toFixed(2));
}

function getIndices() {
  return [
    { symbol: 'SENSEX', name: 'BSE Sensex', value: jitter(81000), changePercent: jitter(0.4, 300) },
    { symbol: 'NIFTY', name: 'Nifty 50', value: jitter(24700), changePercent: jitter(0.3, 300) },
  ];
}

function getCrypto() {
  return [
    { symbol: 'BTC', name: 'Bitcoin', value: jitter(64000), changePercent: jitter(1.2, 300) },
    { symbol: 'ETH', name: 'Ethereum', value: jitter(3400), changePercent: jitter(1.5, 300) },
  ];
}

function getGold() {
  return [{ symbol: 'XAU', name: 'Gold (10g)', value: jitter(72000), changePercent: jitter(0.2, 300) }];
}

function getForex() {
  return [{ symbol: 'USDINR', name: 'USD/INR', value: jitter(83.3, 0.5), changePercent: jitter(0.1, 300) }];
}

// No free source for structured Indian IPO data (dates + price bands) was
// found — every provider checked puts it behind a paid plan. Rather than list
// fictional companies ("Mock Tech Ltd") on a finance app, this returns nothing
// and the client hides the section. IPO *news* still reaches users through the
// dedicated IPO category in the news feed.
function getIpoCalendar() {
  return [];
}

// --- AI-generated daily sections ------------------------------------------
//
// "In focus" and the daily brief are generated from the day's real headlines,
// then cached for AI_TTL_MS. They used to be fixed arrays shuffled at random
// while being labelled AI, which was simply untrue to the user.
//
// Caching matters here: without it every Home screen open would spend Gemini
// quota. One generation per hour serves every user.
const AI_TTL_MS = 60 * 60 * 1000;
const aiCache = { inFocus: null, brief: null };

function fresh(entry) {
  return entry && Date.now() - entry.at < AI_TTL_MS ? entry.data : null;
}

async function headlineBlock() {
  const articles = await newsService.getFeed({ category: 'business', pageSize: 25 });
  return articles
    .slice(0, 25)
    .map((a, i) => `${i + 1}. ${a.title}`)
    .join('\n');
}

/// Companies/assets in today's news. Empty on failure — the client hides the
/// section rather than falling back to invented names.
async function getInFocus() {
  const cached = fresh(aiCache.inFocus);
  if (cached) return cached;

  try {
    const items = await geminiService.inFocus(await headlineBlock());
    if (items.length) aiCache.inFocus = { at: Date.now(), data: items };
    return items;
  } catch (err) {
    console.error('[marketService] inFocus failed:', err.message);
    return [];
  }
}

/// One-sentence market read. Null on failure so the card is hidden.
async function getDailyBrief() {
  const cached = fresh(aiCache.brief);
  if (cached) return cached;

  try {
    const insight = await geminiService.marketBrief(await headlineBlock());
    if (!insight) return null;
    const data = { insight, generatedAt: new Date().toISOString() };
    aiCache.brief = { at: Date.now(), data };
    return data;
  } catch (err) {
    console.error('[marketService] marketBrief failed:', err.message);
    return null;
  }
}

// NOTE: getInsight() and getAiPicks() used to return fixed arrays shuffled at
// random, presented to users as "AI Insight" and "AI Picks". Both are now
// generated by getDailyBrief()/getInFocus() above from the day's real
// headlines. Neither has a canned fallback on purpose: if generation fails the
// section is hidden, rather than showing invented analysis of a market the
// model never saw.

// NOTE: there used to be a getQuotes() here that derived a "price" from a hash
// of the ticker's characters. It fed the portfolio and watchlist screens, so
// users saw invented profit and loss on their own holdings. Portfolio pricing
// now goes through indianMarketService.getLiveQuotes (real Yahoo data, and
// symbols that can't be resolved are omitted rather than faked).

// Crypto is the one section backed by a real provider (CoinGecko, no API key
// needed). Falls back to the mock values if the request fails so the Home
// screen never loses the section entirely.
async function getOverviewLive() {
  const overview = getOverview();

  // Each source is independent; a failure just leaves that section on mock.
  const [liveCrypto, globalStocks, indices, gold, forex] = await Promise.all([
    cryptoService.getPrices(),
    globalMarketService.getGlobalStocks(),
    indianMarketService.getIndices(),
    indianMarketService.getGold(),
    indianMarketService.getForex(),
  ]);

  return {
    ...overview,
    indices: indices || overview.indices,
    crypto: liveCrypto || overview.crypto,
    gold: gold || overview.gold,
    forex: forex || overview.forex,
    // Empty array if the upstream fetch fails — the client hides the
    // section rather than showing a fake one.
    globalMarkets: globalStocks,
  };
}

function getOverview() {
  return {
    indices: getIndices(),
    crypto: getCrypto(),
    gold: getGold(),
    forex: getForex(),
    ipoCalendar: getIpoCalendar(),
  };
}

module.exports = { getOverview, getOverviewLive, getInFocus, getDailyBrief };
